package edu.ndsu.eci.international_capstone_exchange.persist.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _SponsoredProject was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SponsoredProject extends CayenneDataObject {

    public static final String ADDED_PROPERTY = "added";
    public static final String COMPANY_PROPERTY = "company";
    public static final String FILENAME_PROPERTY = "filename";
    public static final String OPEN_PROPERTY = "open";
    public static final String PROJECT_FILE_PROPERTY = "projectFile";
    public static final String PROJECT_TITLE_PROPERTY = "projectTitle";

    public static final String PK_PK_COLUMN = "pk";

    public void setAdded(Date added) {
        writeProperty("added", added);
    }
    public Date getAdded() {
        return (Date)readProperty("added");
    }

    public void setCompany(String company) {
        writeProperty("company", company);
    }
    public String getCompany() {
        return (String)readProperty("company");
    }

    public void setFilename(String filename) {
        writeProperty("filename", filename);
    }
    public String getFilename() {
        return (String)readProperty("filename");
    }

    public void setOpen(Boolean open) {
        writeProperty("open", open);
    }
    public Boolean getOpen() {
        return (Boolean)readProperty("open");
    }

    public void setProjectFile(byte[] projectFile) {
        writeProperty("projectFile", projectFile);
    }
    public byte[] getProjectFile() {
        return (byte[])readProperty("projectFile");
    }

    public void setProjectTitle(String projectTitle) {
        writeProperty("projectTitle", projectTitle);
    }
    public String getProjectTitle() {
        return (String)readProperty("projectTitle");
    }

}
